### PR TITLE
added new methods that accept datetime.datetime object

### PR DESCRIPTION
**Pull request by abelayalew**
i added two additional methods that accept datetime.datetime object and also returns datetime.datetime

### CODE REVIEW

**Comment by rgaudin** [comment]
@abelayalew all of this looks good but changing a remote repo's url and version 🧐?
Is this an accidental PR or is it on purpose? README instructs to use the pypi package I own but you changed the url and version and obviously can't publish there.
Let me know what you ultimately want and we'll sort it out. I'm fine publishing a new version off this.

**Comment by abelayalew** [comment]
@rgaudin 
I was not trying to change the URL, I was trying to add two methods that I think may simplify the conversion process, anyway my concern is to add those two methods to be published here.

**Comment by rgaudin** [comment]
OK, I'll merge that and publish a new version on pypi then. thank you

**Comment by rgaudin** [comment]
backported changes in a single commit using only code changes. Published it on original `ethiopian_date` package as `0.2` as well. thank you !

**Comment by abelayalew** [comment]
thanks for your time, but you still did not add those methods that I was trying to add :point_down: 
image

**Comment by rgaudin** [comment]
Those are not in the pull request…

**Comment by abelayalew** [comment]
okay, i really sorry for that, should i make a pull request again?

**Comment by rgaudin** [comment]
Yes. You should use the master branch of this repo, add your changes and do another PR.
Or just copy/paste the code here and I'll add it as it's just those 2 methods

**Comment by abelayalew** [comment]
okay i created another PR

**Pull request closed without merging**
